In [1]:
import numpy as np

Task 1
    Вкладник поклав 50000 умовних одиниць на три різні рахунки в три різні банки. За першим рахунком виплати становитимуть 5% річних, по другому – 7% річних та по третьому 6% річних. Відомо, що через рік вкладник отримав за відсотками суму в 2250 у.о. з першого та другого банку та суму в 1400 у.о. з першого та третього банку. Скільки умовних одиниць він поклав на кожен рахунок спочатку?

In [2]:
#Task 1
a = np.matrix("1,1,1;0.05,0.07,0;0.05,0,0.06")
b = np.matrix("50000;2250;1400")
x = np.linalg.solve(a, b)
x

matrix([[10000.],
        [25000.],
        [15000.]])

Task 2
    На складі зберігаються мобільні телефони iPhone 6, iPhone 11, iPhone 12 моделей. Всього 1328 екземплярів. Моделей iPhone 6 на 120 менше, ніж моделей iPhone 11, та на 100 більше, ніж моделей iPhone 12. Скільки моделей кожного виду на складі?

In [3]:
#Task 2
a = np.matrix("1,1,1;-1,1,0;-1,0,1")
b = np.matrix("1328;120;-100")
x = np.linalg.solve(a, b)
x

matrix([[436.],
        [556.],
        [336.]])

Task 3
    Складіть канонічне рівняння еліпсоїда, що проходить через три точки A, B, C


In [10]:
matrix = np.array([[3,0,3], [6,1/4,0],[1,1/3,1]])
elipsoid=np.array([1,1,1])
x = np.linalg.solve(matrix, elipsoid)

a = (1/np.sqrt(x[0]), -1/np.sqrt(x[0]))
b = (1/np.sqrt(x[1]), -1/np.sqrt(x[1]))
c = (1/np.sqrt(x[2]), -1/np.sqrt(x[2]))

print(a)
print(b)
print(c)


(3.464101615137755, -3.464101615137755)
(0.7071067811865475, -0.7071067811865475)
(2.0, -2.0)


Task 4
    Складіть рівняння параболи що проходить через задані три точки (1,12), (3,54), (-1,2).Необхідно знайти коефіцієнти рівняння a,b,c.

In [13]:
a = np.array([[1,1,1],[9,3,1],[1,-1,1]], np.float32)
b = np.array([12,54,2], np.float32)
x = np.linalg.solve(a, b)

print(f'Coefficients a={int(x[0])}, b={int(x[1])}, c={int(x[2])}')

Coefficients a=4, b=5, c=3


Task 5
    Складіть функцію get_polynom, яка за набором точок буде знаходити коефіцієнти багаточлена.

In [16]:
def get_polynom(coords):
    b = np.array([])
    items = []
    for x, y in coords:
        array = [x ** i for i in reversed(range(len(coords)))]
        items.append(array)
        b = np.append(b, y)
    a = np.array(items)
    return np.linalg.solve(a, b)

get_polynom([(1, 1), (2, 2), (3, 3)])

array([0., 1., 0.])